### ISSUE TITLE
Use of ILI vs wILI in create_truth

### ISSUE THREAD

**Issue by elray1** [jarad/FluSight#23]
Documentation for create_truth says that "For ‘challege = "ilinet"’ or ‘challenge = "state_ili"’, must contain columns location, week, and wILI."

The verify_ILI_colnames function sets the valid names to the following (last element is "ILI" rather than "wILI"):
valid_names <- c("location", "week", "ILI")

Additionally, the ILI column is used throughout the create_truth, create_onset, create_peak, and create_week functions.

Probably we really want a wILI column, or to allow the user to provide wILI and then map that to whatever gets used in the computations of onset/peak timing and incidence forecasts?

**Comment by craigjmcgowan** [comment]
When I added the functionality for the state-level truth, I changed it to ILI since CDC is not publishing weighted ILI measures for state level data. Not changing the wILI in when `fluview = T` and not fixing the documentation was an oversight on my part. I think I'd like to keep it more general as ILI in the "create" functions but I like the idea of having some code in there to convert wILI to ILI if the user supplies a dataset with wILI instead. 

CDC has also updated the FluView portal to HTML5 which will allow for us to pull state ILI data as well. I put a pull request in to update the `cdcfluview` package and once that's accepted I'll update the `create_truth` code to take advantage of being able to pull that data in automatically.
